//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtbDataTest
    {
        public int id { get; set; }
        public int Code_materiel { get; set; }
        public string Num_serie { get; set; }
        public string Categorie { get; set; }
        public string Modele { get; set; }
        public string Marque { get; set; }
        public string Statut { get; set; }
        public string Fin_garantie { get; set; }
        public string Localisation_dernier { get; set; }
        public string Entite_dernier { get; set; }
        public string Date_inventaire { get; set; }
        public string Date_installation { get; set; }
        public string Localisation_complet { get; set; }
        public string Entite_complet { get; set; }
    }
}
