//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bureau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bureau()
        {
            this.Bien = new HashSet<Bien>();
        }
    
        public Nullable<int> idBatiment { get; set; }
        public int Id_etage { get; set; }
        public int Id_direction { get; set; }
        public int Id_bureau { get; set; }
        public Nullable<int> Code_a_barre { get; set; }
        public string Description { get; set; }
        public int id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bien> Bien { get; set; }
        public virtual Direction Direction { get; set; }
        public virtual Etage Etage { get; set; }
    }
}
