//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public int id { get; set; }
        public string produit { get; set; }
        public Nullable<int> Qte { get; set; }
        public string Emplacement { get; set; }
        public Nullable<int> id_categorie { get; set; }
        public string Num_BonLivraison { get; set; }
        public Nullable<System.DateTime> date_Livraison { get; set; }
        public string Num_BonCommande { get; set; }
        public Nullable<System.DateTime> date_BonCommande { get; set; }
        public string Fournisseur { get; set; }
    
        public virtual Categorie_materiel Categorie_materiel { get; set; }
    }
}
