//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicule()
        {
            this.Association_31 = new HashSet<Association_31>();
            this.Mouvement = new HashSet<Mouvement>();
        }
    
        public Nullable<int> Id_contrat_garanti { get; set; }
        public Nullable<int> idBatiment { get; set; }
        public int Id_parc { get; set; }
        public int Id_Vehicule { get; set; }
        public Nullable<int> Id_fournisseur { get; set; }
        public Nullable<int> Id_societe_assurance { get; set; }
        public Nullable<int> Id_contrat_assurance { get; set; }
        public Nullable<int> Id_societe_maintenance { get; set; }
        public Nullable<int> Id_contrat_maintenance { get; set; }
        public Nullable<int> Id_achat { get; set; }
        public string Matricule { get; set; }
        public string Modele { get; set; }
        public string Etat { get; set; }
        public string Num_sachet { get; set; }
        public Nullable<decimal> Prix_d_achat { get; set; }
    
        public virtual Achat Achat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Association_31> Association_31 { get; set; }
        public virtual Contrat_assurance Contrat_assurance { get; set; }
        public virtual Contrat_garanti Contrat_garanti { get; set; }
        public virtual Contrat_maintenance Contrat_maintenance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mouvement> Mouvement { get; set; }
        public virtual Parc_auto Parc_auto { get; set; }
    }
}
